import { useState } from 'react';
import { ArrowDownToLine, ArrowRight, Bookmark, Check, CircleHelp, ExternalLink, GraduationCap, MapPin, Scale, ShieldCheck, Sparkles, TrendingUp, X } from 'lucide-react';
import { allInterests, currency, majors, schoolInfo, type InterestProfile, type RankingMode, type School, type ScoredMajor } from '../data/majors';
import { MajorIcon, SchoolMark } from './Brand';
import { Modal } from './Modal';

export function Methodology({ onClose, mode }: { onClose: () => void; mode: RankingMode }) {
  return <Modal title="How Wayfinder works" onClose={onClose}>
    <div className="modal-header"><div><div className="eyebrow">A LITTLE TRANSPARENCY</div><h2>Direction, not a crystal ball.</h2></div><button className="icon-button" aria-label="Close methodology" onClick={onClose}><X size={20} /></button></div>
    <div className="methodology-body">
      <p className="modal-lead">Wayfinder helps you explore possibilities. It is an independent planning tool, not an official university ranking or a prediction of your future.</p>
      <section><h3><Sparkles size={18} />Your personalized ranking</h3><p>Passion match is a weighted average of your 16 slider values. Each major emphasizes different interests, and a higher weight means that interest is more relevant to the field. You can see a major's interest weights in its details.</p><div className="weight-breakdown"><span><strong>{mode === 'passion' ? '85' : mode === 'outlook' ? '30' : '60'}%</strong>Passion alignment</span><span><strong>{mode === 'passion' ? '10' : mode === 'outlook' ? '40' : '25'}%</strong>Job demand</span><span><strong>{mode === 'passion' ? '2.5' : mode === 'outlook' ? '15' : '10'}%</strong>Starting pay</span><span><strong>{mode === 'passion' ? '2.5' : mode === 'outlook' ? '15' : '5'}%</strong>AI resilience</span></div><p className="small-copy">These are your current ranking weights. Pay is scaled from 0 at $35,000 to 100 at $85,000 using estimated median pay, with values capped at those bounds. AI resilience is 100 minus AI exposure. Ties use passion match, then major name.</p></section>
      <section><h3><TrendingUp size={18} />Planning estimates, not published statistics</h3><p><strong>Job demand</strong> is an editorial 0-100 planning score for relative career need, expressed as a percentage. It is not a placement rate, employment probability, or projected job-growth percentage. Scores of 80+ are labeled high, 65-79 steady, and below 65 competitive.</p><p><strong>AI disruption</strong> is an illustrative estimate of task exposure to AI over roughly the next 5-10 years, not the percentage chance of losing a job. Low is 0-30%, moderate is 31-55%, and elevated is above 55%. Exposure can mean jobs change, not disappear.</p><p><strong>Average and median starting salaries</strong> are hypothetical U.S. entry-level annual base-pay estimates in USD. They are not observed university outcomes or calculated sample statistics, are not Oregon-specific, and exclude benefits and bonuses. For newly added majors, the illustrated average is simply the estimated median multiplied by 1.06 and rounded to the nearest $1,000. Real pay varies by role, location, employer, and experience.</p></section>
      <section><h3><GraduationCap size={18} />What's in the catalog</h3><p>This static snapshot of the universities' published undergraduate catalogs brings together <strong>{majors.length} distinct major paths</strong>: {majors.filter(major => major.schools.includes('osu')).length} listed at OSU and {majors.filter(major => major.schools.includes('uo')).length} listed at UO. Equivalent majors with different official names share one row; open a major to see its program name at each school. This is not a live university data feed, so use the linked catalogs for the most current offerings.</p><p>We include the separately listed OSU Computer Science - Applied major (restricted to postbaccalaureate students), Forest Engineering - Civil Engineering double-degree major, and Sustainability concurrent double degree. We do not count minors, options, concentrations, graduate-only degrees, certificates, or OSU Honors Scholar tracks as standalone majors.</p></section>
      <section><h3><GraduationCap size={18} />What "best-fit school" means</h3><p>Program names and availability are checked against the universities' public catalogs. If only one offers the directly named major, that school is the recommendation. Where both do, the pick is an editorial program-fit suggestion with a stated rationale, not an objective quality ranking. Related concentrations are identified separately and are not counted as identical majors.</p><p>Career paths are examples, not guarantees. Some need certifications, licensure, a portfolio, or further study. Confirm current admission and degree requirements with each university.</p></section>
      <section className="source-section"><h3><CircleHelp size={18} />Go straight to the source</h3><p>These sources verify program availability and provide labor-market context. They are <strong>not</strong> the source of our illustrative per-major salary, demand, or AI numbers.</p><a href={schoolInfo.osu.url} target="_blank" rel="noreferrer">Oregon State University program catalog<ExternalLink size={14} /></a><a href={schoolInfo.uo.url} target="_blank" rel="noreferrer">University of Oregon undergraduate catalog<ExternalLink size={14} /></a><a href="https://www.bls.gov/ooh/" target="_blank" rel="noreferrer">U.S. Bureau of Labor Statistics: Occupational Outlook Handbook<ExternalLink size={14} /></a><a href="https://www.newyorkfed.org/research/college-labor-market" target="_blank" rel="noreferrer">New York Fed: The Labor Market for Recent College Graduates<ExternalLink size={14} /></a><a href="https://www.ilo.org/publications/generative-ai-and-jobs-refined-global-index-occupational-exposure" target="_blank" rel="noreferrer">ILO: Generative AI and Jobs (2025)<ExternalLink size={14} /></a></section>
      <div className="privacy-note"><ShieldCheck size={18} /><p>Your interests and saved majors stay in this browser's local storage. There is no account, and your profile is not sent to a server. Clearing browser data removes your workspace.</p></div>
    </div>
  </Modal>;
}

export function Comparison({ items, onClose, saved, onSave }: { items: ScoredMajor[]; onClose: () => void; saved: string[]; onSave: (id: string) => void }) {
  return <Modal title="Compare your possibilities" onClose={onClose} wide>
    <div className="modal-header"><div><div className="eyebrow">SIDE BY SIDE</div><h2>Different paths. A clearer picture.</h2></div><button className="icon-button" aria-label="Close comparison" onClick={onClose}><X size={20} /></button></div>
    <div className="comparison-scroll"><table className="comparison-table"><caption className="sr-only">Comparison of selected majors. Market, AI, and salary values are illustrative planning estimates.</caption><thead><tr><th>What matters to you</th>{items.map(major => <th key={major.id}><MajorIcon category={major.category} /><h3>{major.name}</h3><button className={`text-button ${saved.includes(major.id) ? 'is-saved' : ''}`} onClick={() => onSave(major.id)}><Bookmark size={14} fill={saved.includes(major.id) ? 'currentColor' : 'none'} />{saved.includes(major.id) ? 'Saved to shortlist' : 'Save major'}</button></th>)}</tr></thead><tbody>
      <tr><th>Overall ranking score</th>{items.map(major => <td key={major.id}><strong className="comparison-score">{major.score}<small>/100</small></strong></td>)}</tr>
      <tr><th>Passion match</th>{items.map(major => <td key={major.id}><strong className="green-text">{major.passion}%</strong></td>)}</tr>
      <tr><th>Best-fit school</th>{items.map(major => <td key={major.id}><SchoolMark school={major.bestSchool} full /></td>)}</tr>
      <tr><th>Job demand estimate</th>{items.map(major => <td key={major.id}>{major.demand}%<span className="cell-caption">Relative need score</span></td>)}</tr>
      <tr><th>AI disruption estimate</th>{items.map(major => <td key={major.id}>{major.ai}%<span className="cell-caption">Task exposure, not job loss</span></td>)}</tr>
      <tr><th>Average starting salary</th>{items.map(major => <td key={major.id}>{currency(major.average)}<span className="cell-caption">Illustrative annual base pay</span></td>)}</tr>
      <tr><th>Median starting salary</th>{items.map(major => <td key={major.id}>{currency(major.median)}</td>)}</tr>
      <tr><th>Possible career paths</th>{items.map(major => <td key={major.id}><ul className="plain-list">{major.careers.map(career => <li key={career.title}>{career.title}</li>)}</ul></td>)}</tr>
      <tr><th>Skills you could use</th>{items.map(major => <td key={major.id}><p>{[...new Set(major.careers.flatMap(career => career.skills))].slice(0, 6).join(', ')}</p></td>)}</tr>
      <tr><th>Why this university?</th>{items.map(major => <td key={major.id}><p>{major.schoolReason}</p></td>)}</tr>
    </tbody></table></div>
    <div className="comparison-footer"><CircleHelp size={15} /><p>Market, AI, and salary figures are planning scenarios, not measured outcomes. Use them as a starting point, not a promise.</p></div>
  </Modal>;
}

export function Universities({ onExplore }: { onExplore: (school: School) => void }) {
  return <div>
    <div className="page-heading"><div><div className="eyebrow">ROOTED IN OREGON</div><h1>Two schools. So many possibilities.</h1><p>Different strengths, shared ambition. Get to know your options.</p></div></div>
    <div className="university-intro"><Scale size={23} /><div><h2>The right school is personal.</h2><p>Start with the program, then explore the campus, costs, and community. There isn't one winner for everyone.</p></div></div>
    <div className="university-grid">{(['osu', 'uo'] as School[]).map(school => <section className={`university-panel ${school}`} key={school}>
      <div className="university-masthead"><SchoolMark school={school} /><span>PUBLIC RESEARCH UNIVERSITY</span></div>
      <h2>{schoolInfo[school].name}</h2><p className="campus-location"><MapPin size={14} />{schoolInfo[school].city}</p>
      <p className="university-description">{school === 'osu' ? 'An applied, hands-on setting for people who want to understand the world and build something better.' : 'A creative, collaborative setting for people who want to ask big questions and bring fresh perspectives.'}</p>
      <h3>Paths worth exploring</h3><ul className="university-strengths">{(school === 'osu' ? ['Engineering & applied technology', 'Forestry & environmental sciences', 'Agriculture, health & natural resources', 'Business, science & the liberal arts'] : ['Architecture, design & the arts', 'Journalism & communication', 'Psychology & the social sciences', 'Business, computing & data science']).map(item => <li key={item}><Check size={14} />{item}</li>)}</ul>
      <div className="university-program-count"><strong>{majors.filter(major => major.schools.includes(school)).length}</strong><span>directly offered majors<br />in this comparison</span></div>
      <button className="button button-primary full" onClick={() => onExplore(school)}>Explore {school === 'osu' ? 'Oregon State' : 'UO'} majors<ArrowRight size={16} /></button>
      <a className="university-catalog" href={schoolInfo[school].url} target="_blank" rel="noreferrer">Visit the official program catalog<ExternalLink size={14} /></a>
    </section>)}</div>
    <section className="university-next"><GraduationCap size={27} strokeWidth={1.5} /><div><h2>Make it real. Visit, ask, explore.</h2><p>Ask an advisor about degree requirements, accreditation, financial aid, internship access, and whether the program fits how you like to learn.</p></div></section>
  </div>;
}

export function WorkspaceInfo({ onClose, onReset, profile, saved, personalized }: { onClose: () => void; onReset: () => void; profile: InterestProfile; saved: string[]; personalized: boolean }) {
  const [confirmReset, setConfirmReset] = useState(false);
  const exportWorkspace = () => {
    const data = JSON.stringify({ interests: Object.fromEntries(allInterests.map(({ key, label }) => [label, profile[key]])), savedMajors: majors.filter(major => saved.includes(major.id)).map(major => major.name), personalized, note: 'Market and salary values in Wayfinder are illustrative planning estimates.' }, null, 2);
    const url = URL.createObjectURL(new Blob([data], { type: 'application/json' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'wayfinder-workspace.json'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <Modal title="Your local workspace" onClose={onClose}>
    <div className="modal-header"><div><div className="eyebrow">YOUR SPACE TO EXPLORE</div><h2>Saved here. Just for you.</h2></div><button className="icon-button" aria-label="Close workspace settings" onClick={onClose}><X size={20} /></button></div>
    <div className="workspace-info"><ShieldCheck size={36} strokeWidth={1.4} /><p>Your profile and {saved.length} saved {saved.length === 1 ? 'major live' : 'majors live'} in this browser. No login. No cloud storage. Export a copy before clearing your browser data.</p><button className="button button-secondary" onClick={exportWorkspace}><ArrowDownToLine size={16} />Export my workspace</button><div className="workspace-reset"><h3>{confirmReset ? 'Ready to reset your workspace?' : 'A fresh start?'}</h3><p>Reset clears your saved majors and returns your interest profile to the sample settings. This cannot be undone.</p>{confirmReset ? <div className="reset-actions"><button className="button button-secondary" onClick={() => setConfirmReset(false)}>Keep my workspace</button><button className="button button-primary" onClick={onReset}>Yes, start fresh</button></div> : <button className="text-button danger-text" onClick={() => setConfirmReset(true)}>Reset my workspace</button>}</div></div>
  </Modal>;
}